name: avatende
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  toast: ^0.3.0
  flutter_slidable: ^1.2.1
  brasil_fields: ^1.4.4
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  provider: ^6.0.2
  firebase_database: ^9.0.14
  ndialog: ^4.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_speed_dial: ^6.0.0

  #using to PDF writer
  pdf: ^3.8.0
  flutter_pdfview: ^1.2.2
  share_extend: ^2.0.0 #compartilhar pdf
  path_provider: ^2.0.10
  advance_pdf_viewer: ^2.0.1

  #using to EXCELL writer
  excel: ^2.0.0-null-safety-3

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get_it: ^7.2.0
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.16
  firebase_analytics: ^9.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/icon.png
    - assets/images/addImage.png
    - assets/images/profileDefault.png

scripts:
  mobx_run: flutter pub run build_runner build
  mobx_run_watch: flutter pub run build_runner watch
  mobx_run_del: flutter pub run build_runner build --delete-conflicting-outputs
  laucher_icons: flutter pub run flutter_launcher_icons:main
