name: avatende
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_pro: ^1.0.0
  toast: ^0.1.5
  flutter_slidable: ^0.5.7
  brasil_fields: ^0.4.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.0
  cloud_firestore: ^0.14.0
  provider:
  firebase_database:
  ndialog: ^4.1.1
  flutter_datetime_picker: ^1.4.0
  flutter_speed_dial: ^2.1.1

  #using to PDF writer
  pdf: ^2.1.0
  flutter_full_pdf_viewer: ^1.0.6
  share_extend: "^1.1.9" #compartilhar pdf
  path_provider: ^1.6.28
  advance_pdf_viewer: any

  #using to EXCELL writer
  excel: ^1.1.5

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get_it: ^5.0.1
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  splashscreen: ^1.3.3
  image_picker: ^0.6.7+22
  firebase_storage: ^4.0.1
  firebase_analytics: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - images/icon.png
    - images/background.jpg

scripts:
  mobx_run: flutter pub run build_runner build
  mobx_run_watch: flutter pub run build_runner watch
  mobx_run_del: flutter pub run build_runner build --delete-conflicting-outputs
  laucher_icons: flutter pub run flutter_launcher_icons:main
